pipelines:
  default:
    - step:
        name: Build project
        services:
          - jdk
        caches:
          - gradle
          - gradlewrapper
        script:
          - bash ./gradlew build
  branches:
    master:
      - step:
          name: Build project
          services:
            - jdk
          caches:
            - gradle
            - gradlewrapper
          script:
            - bash ./gradlew build
      - step:
          name: Release project
          services:
            - jdk
          caches:
            - gradle
            - gradlewrapper
          trigger: manual
          script:
            - git config --global user.email "bitbucketci-team@atlassian.com"
            - git config --global user.name "Bitbucket Pipelines"
            - bash ./gradlew release -Prelease.customKeyFile="/opt/atlassian/pipelines/agent/data/id_rsa"
            - bash ./gradlew publish
definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
  services:
    jdk:
      image: openjdk:8
      memory: 2048
